# -*- coding: utf-8 -*-
"""1_Warm-up with Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1abvmqJFqVaQooMtj-05zDD-oirAFuCRT

Write a command to get the Python version you are using.
"""

!python --version

"""Write a python script to print Hello Python on the screen directly in the command
line.
"""

print("Hello Python")

"""Write a python script and store it in a file and execute the file from the command line."""

!python "/content/hello.py"

"""Write a python script to print Hello on the first line and Python on the second line"""

print("Hello","Python",sep="\n")

"""Write a python script to print “MySirG” on the screen"""

print("MySirG")

"""Write a python script to print “Teacher’s Day” on the screen"""

print("Teacher's Day")

"""Write a python script to print the value of a variable. Variable contains your name as
data.
"""

name = "Asim"
print(name)

"""Write a python script to create variables to store your name, age, qualification, years
of experience and print it.
"""

name = "asim"
age = 22
qual = "MS"
yrs = 3

print(f"Name={name}, Age={age}, Qua;ification={qual}, Years of Experience={yrs} ")

"""Write a python script to print values of three variables, each in a new line. Variable
contains integer values
"""

num1 = 100
num2 = 200
num3 = 300
print(num1,num2,num3,sep="\n")